/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ContextMenu: typeof import('./../components/ContextMenu/index.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    'IMynaui:chatMessages': typeof import('~icons/mynaui/chat-messages')['default']
    'IMynaui:checkCircle': typeof import('~icons/mynaui/check-circle')['default']
    'IMynaui:cog': typeof import('~icons/mynaui/cog')['default']
    'IMynaui:dazeCircle': typeof import('~icons/mynaui/daze-circle')['default']
    'IMynaui:file': typeof import('~icons/mynaui/file')['default']
    'IMynaui:folderTwo': typeof import('~icons/mynaui/folder-two')['default']
    'IMynaui:gridOne': typeof import('~icons/mynaui/grid-one')['default']
    'IMynaui:home': typeof import('~icons/mynaui/home')['default']
    'IMynaui:list': typeof import('~icons/mynaui/list')['default']
    'IMynaui:moon': typeof import('~icons/mynaui/moon')['default']
    'IMynaui:sun': typeof import('~icons/mynaui/sun')['default']
    'IMynaui:upload': typeof import('~icons/mynaui/upload')['default']
    'IMynaui:userCircle': typeof import('~icons/mynaui/user-circle')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
